# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03c_data.core.ipynb.

# %% auto 0
__all__ = ['Component', 'Label']

# %% ../../nbs/03c_data.core.ipynb 2
from fastcore.all import *
import polvo as pv

# %% ../../nbs/03c_data.core.ipynb 3
# Still needs to be figured out
class Component:
    ...

# %% ../../nbs/03c_data.core.ipynb 4
class Label:
    def __init__(self, id, name): store_attr()
    def __repr__(self): return f'{self.id}: {self.name}'
