# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03c_data.core.ipynb.

# %% auto 0
__all__ = ['Component', 'ImageFile']

# %% ../../nbs/03c_data.core.ipynb 2
from fastcore.all import *
import polvo as pv

# %% ../../nbs/03c_data.core.ipynb 3
class Component:
    def show(self, image):
        raise NotImplementedError

# %% ../../nbs/03c_data.core.ipynb 4
class ImageFile(Component):
    def __init__(self, file):
        self.file = file
        
    def show(self, image=None):
        if image: raise ValueError('Image passed to show should be None, this should be the first component in the list.')
        return pv.open_image(self.file)
