# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10e_bbox.vis.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/10e_bbox.vis.ipynb 3
import PIL
import numpy as np
import polvo as pv
from typing import Tuple
from PIL import Image
from PIL.ImageDraw import ImageDraw
from . import BBox
