# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01m_utils.downoad.ipynb.

# %% auto 0
__all__ = ['download', 'download_and_extract']

# %% ../../nbs/01m_utils.downoad.ipynb 2
from fastcore.all import *
import polvo as pv

# %% ../../nbs/01m_utils.downoad.ipynb 4
def download(url, save_dir, chunk_size=1024):
    """Download file from url"""
    import requests
    r = requests.get(url, stream=True)
    save_path = Path(save_dir)/Path(url).name
    with open(str(save_path), "wb") as f:
        bar_total = r.headers.get("Content-Length")
        bar = pv.pbar(unit="B", total=int(bar_total) if bar_total else None)
        for chunk in r.iter_content(chunk_size=chunk_size):
            if chunk:  # filter out keep-alive new chunks
                bar.update(len(chunk))
                f.write(chunk)
    return save_path

# %% ../../nbs/01m_utils.downoad.ipynb 5
def download_and_extract(url, save_dir, chunk_size=1024):
    save_path = download(url=str(url), save_dir=save_dir, chunk_size=chunk_size)
    import shutil; shutil.unpack_archive(filename=str(save_path), extract_dir=str(save_dir))
