# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01t_utils.misc.ipynb.

# %% auto 0
__all__ = ['kwargs_grid', 'safe_zip', 'test_script']

# %% ../../nbs/01t_utils.misc.ipynb 2
from fastcore.all import *
import numbers
import polvo as pv

from PIL import Image

# %% ../../nbs/01t_utils.misc.ipynb 3
def kwargs_grid(**kwargs):
    "Returns a generator with all combinations of kwargs"
    return (dict(zip(kwargs.keys(), v)) for v in itertools.product(*kwargs.values()))

# %% ../../nbs/01t_utils.misc.ipynb 5
@functools.wraps(zip)
def safe_zip(*args, **kwargs):
    if len(set(map(len, args))) not in (0, 1):
        raise ValueError(f'All elements should have the same size, but got {[len(x) for x in args]}')
    return zip(*args, **kwargs)

# %% ../../nbs/01t_utils.misc.ipynb 8
@pv.call_parse
def test_script(msg:Param("The message", str),
                upper:Param("Convert to uppercase?", store_true)):
    "Print `msg`, optionally converting to uppercase"
#     print(msg.upper() if upper else msg)
    return msg.upper() if upper else msg
